### ISSUE TITLE
Changing the uploaded file should reset all the values

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#112]
## Current behavior

When changing the current uploaded file, the mappings selected remains as is and then clicking review button will break the app flow, as the mappings were selected as per the previous file and current file might not have those colunms.

## Expected behavior

When changing the file, all the values should reset to default.

## Steps to reproduce the issue

1. Upload a file
2. Select a mapping
3. Change the uploaded file
4. See that the select mapping remains as is, but all the values should reset to default

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
Conclusion- https://github.com/hotwax/import/pull/118#issuecomment-1379919376
