### ISSUE TITLE
Integrate field mappings feature with API

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/import#129]
## What is the motivation for adding/enhancing this feature?

Currently, we store field mappings in localstorage, use APIs to store it at backend.

APIs:

createDataManagerMapping
Parameters:
mappingPrefId (optional)
mappingPrefValue
mappingPrefTypeEnumId
fromDate
thruDate

updateDataManagerMapping
Parameters:
mappingPrefId (optional)
mappingPrefValue
mappingPrefTypeEnumId
fromDate
thruDate

deleteDataManagerMapping
Parameters:
mappingPrefId

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
**Delete Mapping Modal**
![Delete Mapping Modal](https://user-images.githubusercontent.com/119936391/212258910-634e8161-2936-47dd-8d15-d516f0ce1c6e.png)

**New mappings saved Toast**
![New mappings saved Toast](https://user-images.githubusercontent.com/119936391/212258977-561850f7-35f6-486f-938b-346ad8803a9a.png)

**CSV changes saved toast**
![CSV changes saved toast](https://user-images.githubusercontent.com/119936391/212258989-df4a5952-f72f-436e-915f-755bfd23b9c8.png)

**Comment by shashwatbangar** [comment]
> **Delete Mapping Modal** ![Delete Mapping Modal](https://user-images.githubusercontent.com/119936391/212258910-634e8161-2936-47dd-8d15-d516f0ce1c6e.png)
> 
> **New mappings saved Toast** ![New mappings saved Toast](https://user-images.githubusercontent.com/119936391/212258977-561850f7-35f6-486f-938b-346ad8803a9a.png)
> 
> **CSV changes saved toast** ![CSV changes saved toast](https://user-images.githubusercontent.com/119936391/212258989-df4a5952-f72f-436e-915f-755bfd23b9c8.png)

Thanks a lot for this. Will be really helpful.

**Comment by shashwatbangar** [comment]
Reference - https://github.com/hotwax/press-release-faq/blob/main/import/save-csv-maps-for-po.md
