### ISSUE TITLE
Implement static UI for missing sku modal

### ISSUE THREAD

**Issue by disha1202** [hotwax/import#150]
## What is the motivation for adding/enhancing this feature?

Missing Products Modal helps users to correct missing/wrong product SKU codes. User can select one SKU code at a time, the selected SKU code would appear in the input box letting user edit or rewrite the SKU code. Once done, user can update the SKU code. Once the user press the Update button, API will take the input and also fetch the product SKU code from the product information database. Following, there will be two results scenarios:

1. If SKU codes match, input is valid and product will move to the completed tab.
2. If SKU codes do not match, input is invalid and user must put the different SKU code. Note: User can abandon correcting the one SKU code and might move to other incorrect SKU code.

![image](https://user-images.githubusercontent.com/58461801/212889654-824bad8f-b55c-47cb-bc58-872dbc64c79e.png)
![image](https://user-images.githubusercontent.com/58461801/212889684-724debf0-921b-491e-ba9f-d3a8055fd2d4.png)
![image](https://user-images.githubusercontent.com/58461801/212889718-69c9f249-b04d-44d1-9b92-e10dcba42cd8.png)

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
Closing as merged
