### ISSUE TITLE
Mapping saved the first time after login fails

### ISSUE THREAD

**Issue by appurvajain** [hotwax/import#193]
## Current behavior
When a user logs in for the first time and creates a mapping, it does not save. However, when we logout and login again, the earlier saved mapping is visible.
It is only the first time user logs in that the mapping cannot be saved, the second time we are able to create mappings and save them successfully.
We have tested this on demo-oms and dev-hc instances.

## Expected behavior
The user should be able to log in and save the mapping without any fail message.

## Steps to reproduce the issue
Follow these steps:
1. Login into an account
2. Create a mapping and click on save
3. The error message will appear.
4. Logout and login again, the saved mapping will appear.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
The issue is not related to login, instead it occurs whenever there is no field mapping found on initial load for PO or inventory.
