### ISSUE TITLE
Unable to see the field mapping options after uploading a file on inventory page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#204]
## Current behavior

When uploading a file on inventory page the field selection options are not visible.

## Expected behavior

After uploading a file, user should be able to map the fields

## Steps to reproduce the issue

1. Go to inventory page
2. Upload a file
3. See that we are unable to map the fields

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

The issue is because having an error in console regarding the the logger being undefined on inventory page

## Screenshot
![image](https://user-images.githubusercontent.com/41404838/227433532-a5704bf6-fc8f-4368-82c4-897eccdd22bd.png)

**Comment by k2maan** [comment]
This happens only when the values in the CSV are not formatted correctly. Will implement a toast message and disable the review button.
