### ISSUE TITLE
Remove Pointer Effect on Chips Hover

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#228]
## Current behavior
Currently, there is a pointer effect applied when a user hovers over the chips on the Purchase Order and Inventory Review page. This effect is not aligned with our design requirements or user experience goals.

## Expected behavior
The pointer effect should not appear as these chips are not clickable.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Deven-ai12** [comment]
can you assign this issue

**Comment by dt2patel** [comment]
Not a priority issue reported by clients. Closing issue
