### ISSUE TITLE
Implement Spinner in Timezone Model for Timezone Configuration

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#233]
In the timezone configuration section, it's crucial to provide visual feedback to users while the application fetches and processes timezone data. Currently, there is a lack of visual cues, leading to potential user confusion. To enhance the user experience, we propose implementing a spinner in the timezone model. This spinner will indicate loading activity, ensuring users are aware of the system processing their request.

**Acceptance Criteria**

The spinner is visible within the timezone model when the application is fetching timezone data and disappears once the timezone data has been successfully loaded and displayed in the timezone configuration section.

**Comment by Nidbhagwat** [comment]
Here is the Figma link for the UI:

https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=25927%3A167687&mode=design&t=xRUxJOC64740RaOJ-1

**Comment by gyaneshwarchoudhary** [comment]
I am intrested in contributing to this issue,
can you please assign it to me?

**Comment by Dhiraj1405** [comment]
> I am intrested in contributing to this issue,
> can you please assign it to me?

Sure, go ahead

**Comment by HarshalMahajan0110** [comment]
can you assign me?
