### ISSUE TITLE
Integrate DXP Component: App Version Info on the Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#235]
## What is the motivation for adding/enhancing this feature?
Integrate the DXP component "App Version Info" into the Settings page of the application. This addition will provide users with essential information about the version of the application they are currently using. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by MAKTECH7** [comment]
can you assign me

**Comment by k2maan** [comment]
@MAKTECH7 sure, go ahead

**Comment by Adameddy26** [comment]
Verified and working fine in v2.15.0.
https://jam.dev/c/809d9f51-5579-4cec-ae3f-70d4f1655656
