### ISSUE TITLE
Enhance Permission Management and Access Restrictions

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#244]
## What is the motivation for adding/enhancing this feature?
To improve the security and functionality of the Preorder Management app, we propose the following modifications for different user roles:

### Permission Management for Super Users and Admin Users:

**Refine the permission system to ensure**

- Super Users have unrestricted access to all features and configurations.
- Admin Users have complete permissions similar to Super Users.

**Permission Management for Merchandising Managers**

- Restrict access to the Inventory page.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.15.0.
https://jam.dev/c/e8f2c23b-c760-4167-919b-566c6434ed08
