### ISSUE TITLE
Implement Support for Different Product Identifiers in Inventory import

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#251]
## What is the motivation for adding/enhancing this feature?
Our current system relies on a specific product identifier format, and there is a growing need to support various product identifier types such as UPCA and SKU to accommodate diverse product catalogs and industry standards. To enhance the flexibility and compatibility of our system, we propose implementing support for different product identifiers. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
The support of different product identifier in inventory upload is done in the following PR - 
https://github.com/hotwax/import/pull/255
