### ISSUE TITLE
Remove Location Seq ID Check as Required Field

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/import#252]
## What is the motivation for adding/enhancing this feature?
In our current system, the Location Seq ID is designated as a required field, causing constraints and potential usability issues for certain workflows. To improve flexibility and user experience, we propose removing the Location Seq ID check as a required field. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
We removed locationSeqId from inventory import workflow under this - 

https://github.com/hotwax/import/pull/255
