### ISSUE TITLE
Uploading a file displays two success toast

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#267]
## Current behavior

When uploading a file on the inventory page, two toast gets displayed on successful upload.

## Expected behavior

Only a single toast should be dispalyed

## Steps to reproduce the issue

1. Go to inventory page
2. Upload a file
3. Dismiss the toast, and you will see the same toast behind the previous toast.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.15.0.
https://jam.dev/c/0b89cee4-f1d1-41c5-a553-db39aaf5fe04
