### ISSUE TITLE
When using oms complete url to login, the redirection to commerce from inventory detail and PO detail page fails

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#268]
## Current behavior

After successfully uploading an inventory or PO file, a toast gets displayed to view the uploaded file in commerce, that does not work when the user is logged-in into the app using complete URL `https://<oms>.hotwax.io/api`.

## Expected behavior

The redirection should always work irrespective of the oms pattern, user used to logged-in into the app.

## Steps to reproduce the issue

1. Log into the app using `https://<oms>.hotwax.io/api` as the oms name
2. Upload inventory or PO file
3. Click on the `View` button in the toast to get redirected to the commerce and verify that the page does not open

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in v2.15.0.
https://jam.dev/c/1520b71c-4c5a-438b-b211-590afeae4f97
