### ISSUE TITLE
Scheduled Restock UI

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/import#285]
## Description
To enhance the user interface of the Import App, making it more intuitive, efficient, and visually appealing. The new UI should improve user experience by simplifying workflows, reducing cognitive load, and providing a modern look and feel.

## Additional information
https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=37259-56441&t=Z2mGddpcQwqrWH24-11

**Comment by ravilodhi** [comment]
@Adameddy26 Same here, if tested close this issue else plan testing on this. Part of following release - https://github.com/hotwax/import/releases/tag/v2.18.0

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.18.1. Hence, closing this ticket.
