### ISSUE TITLE
Currently we are passing externalFacilityId in the scheduled restock, but need to change it to facilityId

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#289]
## What is the motivation for adding/enhancing this feature?

As in the app, we are fetching all the facilities from the system then instead of passing externalId for facility, pass the facilityId.
Doing so, as there might be cases where externalFacilityId mapping is missing for some facility which will result in having issues in the overall process.

## What are the acceptance criteria?

- [x] Pass facilityId in place of externalFacilityId when creating shipment, also update the parameter name from `externalDestinationFacilityId` to `destinationFacilityId`
- [x] Update the viewSize when fetching facilities to 250

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v2.18.1. Hence, closing this ticket.
