### ISSUE TITLE
Jobs are not filtered on the basis runTime

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#291]
## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by G0V1NDK** [comment]
Tested on newera-uat (https://import-dev.hotwax.io/scheduled-restock). Working as expected.
App Version: MAIN-C83E525

![image](https://github.com/user-attachments/assets/52119380-3bd3-4c72-b0bf-92874aff72cc)

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.18.1. Hence, closing this ticket.
![image](https://github.com/user-attachments/assets/0705ee79-2ece-4909-9279-56d43e653527)
