### ISSUE TITLE
Make the selected mapping chip appear highlighted.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/import#295]
## What is the motivation for adding/enhancing this feature?

Currently when we select any mapping field or create new mapping its chip dont appear as selected which creates confusion as which chip is selected.

Make the selected mapping chip appear highlighted for better user experience.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified in release v2.18.1 and found that when user closes the new mapping modal without any change then in that case highlighting gets removed from the chip.
Hence, reopening this issue.

**Comment by priyanshee1604** [comment]
Verified the changes in the app's development environment and confirmed that the following scenarios are working as expected:

Case 1: When the user selects a mapping chip, it is displayed as selected/highlighted.
Case 2: When the user creates a new mapping, it is displayed as selected/highlighted.
Case 3 (Reopened Issue): If the user selects a saved mapping, opens the new mapping modal, and closes it without making any changes, the selection on the mapping remains intact.
