### ISSUE TITLE
Update oms version to v1.15.1

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/import#298]
## What is the motivation for adding/enhancing this feature?
oms-api v1.15.1 includes a fix to call solr-query api using POST method instead of GET.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v2.18.1. Hence, closing this ticket.
