### ISSUE TITLE
Cursor should change to pointer for drop down action menu for records

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/import#64]
Steps to navigate to Purchase Order Details page

1. Login into application
OMS: dev-apps
Username: aaron.wagner
password: Aaron@123

2. Upload the below CSV:
[DM12234_SUMPO111111.csv](https://github.com/hotwax/import/files/9725012/DM12234_SUMPO111111.csv)

3. Select appropriate fields and click on Review
![image](https://user-images.githubusercontent.com/15027245/194320599-b25da494-f3a0-407c-99d8-b0d890a5c14a.png)

4. Open action menu for individual records, actions should cursor as pointer
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/15027245/194318810-e8c7ac0c-e546-42e6-ad1e-8b1385eb6e29.png">

**Comment by error707-persona** [comment]
can i work on this?

**Comment by adityasharma7** [comment]
> can i work on this?

@error707-persona Sure
