### ISSUE TITLE
Add PR and Issue template

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/import#67]
Reference: https://github.com/hotwax/job-manager/tree/main/.github

**Comment by kaustav202** [comment]
can I work on this @ymaheshwari1

**Comment by ymaheshwari1** [comment]
Sure @kaustav202, go ahead.

**Comment by ymaheshwari1** [comment]
> Should I make separate prs for each @ymaheshwari1 ?
You can do it in a single PR.
