### ISSUE TITLE
Purchase order data is not cleared on logout.

### ISSUE THREAD

**Issue by disha1202** [hotwax/import#73]
## Current behavior

Purchase order data is not cleared on logout.
## Steps to reproduce the issue

1. Login to the application.
2. Upload PO CSV
3. Map the fields.
4. Click on review button.
5. Navigate to settings page and logout.
6. Login again and you find the previous PO Uploaded and fields mapped.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by shashwatbangar** [comment]
@disha1202 I am not able to re-generate this issue can you help me out?
I followed the steps to re-produce but seems like it is working fine.

https://user-images.githubusercontent.com/62360781/210241212-a7964214-69ce-4be5-929e-ad9001eaadbd.mov
