### ISSUE TITLE
Reseting reverts to wrong info

### ISSUE THREAD

**Issue by dt2patel** [hotwax/import#74]
## Current behavior
When clicking on revert on a style, the ordered qty is not reverted to what was uploaded. Rather it seems like its changed to what the first item has.

## Expected behavior
It should change back to what was initially uploaded

## Steps to reproduce the issue
Upload PO, adjust qty with buffer and click reset.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x ] NO

**Comment by disha1202** [comment]
Verified the issue.
Instead of just quantity, all the fields such as product name, arrival date, etc are changed to what the first item has.
