### ISSUE TITLE
Make file name easier to see

### ISSUE THREAD

**Issue by dt2patel** [hotwax/import#79]
## What is the motivation for adding/enhancing this feature?

After uploading a file it's not immediately obvious if the file uploaded and what the name of the file was.

## What are the acceptance criteria?
The file name should be closer to the upload button so the user can see it if they're about to re-upload a file. It should also be bold so it stands out on the page.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

**Comment by adityasharma7** [comment]
This is already done. We could work on improving the UI, there should be some spacing between the label and file name

![image](https://user-images.githubusercontent.com/15027245/203307804-56c802dd-1b50-44ba-88e8-5bff37ca675c.png)
